2018-06-25 11:24:20,108 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 11:24:31,488 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 11:24:41,731 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 11:25:03,763 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 11:28:20,918 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 13:20:19,444 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 14:02:20,267 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 14:06:58,911 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 14:08:04,602 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 14:19:13,303 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 14:22:08,767 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 14:22:18,593 ERROR: Exception on /translate [POST] [in /home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-06-25 14:24:34,198 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 14:30:40,494 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:17:56,951 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:30:04,277 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:36:31,991 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:40:34,656 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:41:00,979 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:49:27,201 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:52:21,711 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:54:06,468 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:55:25,047 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:58:26,730 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 15:59:00,239 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 16:07:17,748 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 16:11:01,345 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 16:11:37,726 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 16:12:15,624 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 16:14:02,961 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 16:29:47,698 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 16:39:17,078 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 17:27:37,181 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 23:21:35,017 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 23:21:47,488 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 23:55:45,302 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 23:55:50,056 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-25 23:58:43,051 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-27 17:54:33,980 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:77]
2018-06-27 17:56:05,290 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:77]
2018-06-27 17:56:05,290 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:77]
2018-06-27 18:14:55,089 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:77]
2018-06-27 20:21:12,614 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:77]
2018-06-27 20:21:20,824 ERROR: Exception on / [GET] [in /home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/home/duan/Flask_microblog/app/main/routes.py", line 19, in before_request
    g.locale = 'zh-cn' if str(get_locale()).startswith('zh') else str(get_locale())    # get_locale() returns a locale obj; use str() to get lang code.
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/home/duan/Flask_microblog/app/__init__.py", line 84, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'app' is not defined
